# Generated by Django 3.1.2 on 2020-10-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
