# Generated by Django 3.1.2 on 2020-10-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobApp', '0002_auto_20201025_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
